# Generated by Django 5.0.6 on 2025-01-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(default='Description goes here', max_length=120),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default='New Task', max_length=200),
        ),
    ]
